inputs:
  working-directory: 
    description: 'Working directory where package.json can be found'
    default: '.'
runs:
  using: "composite"
  steps: 
    - name: Extract contributed themes from package.json
      id: themes
      shell: bash
      env:
        WORKING_DIR: ${{ inputs.working-directory }}
      run: |
        value=$(jq '.contributes.themes[].path' "$WORKING_DIR/package.json" --raw-output)
        echo "value<<EOF" >> $GITHUB_OUTPUT
        echo "$value" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Verify each contributed theme exists
      shell: bash
      env:
        WORKING_DIR: ${{ inputs.working-directory }}
        THEMES: ${{ steps.themes.outputs.value }}
      run: |
        errors=0
        for theme in $THEMES; do
          filepath="$WORKING_DIR/$theme"
          if (!(test -f "$filepath")); then
            echo "ERROR: File not found: $filepath"
            errors+=1
          fi
        done
        exit $errors
