// https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/format-datetimefunction

format_datetime(datetime(2015-12-14 02:03:04.12345), 'y-M-d h:m:s.fffffff') == "15-12-14 2:3:4.1234500"
format_datetime(datetime(2015-12-14 02:03:04.12345), "y-M-d h:m:s.fffffff") == "15-12-14 2:3:4.1234500"

let dt = datetime(2017-01-29 09:00:05);
print 
v1=format_datetime(dt,'yy-MM-dd [HH:mm:ss]'), 
v2=format_datetime(dt, 'yyyy-M-dd [H:mm:ss]'),
v3=format_datetime(dt, 'yy-MM-dd [hh:mm:ss tt]')
