// https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/rangeoperator

range LastWeek from ago(7d) to now() step 1d;

range Steps from 1 to 8 step 3;

range TIMESTAMP from ago(4h) to now() step 1m
| join kind=fullouter
  (Traces
      | where TIMESTAMP > ago(4h)
      | summarize Count=count() by bin(TIMESTAMP, 1m)
  ) on TIMESTAMP
| project Count=iff(isnull(Count), 0, Count), TIMESTAMP
| render timechart
