# Retry up to {{ max-retries }} times. Helpful if there is contention on the main
# branch, e.g. from many workflows simultaneously trying to push automated commits.
inputs:
  max-retries: 
    description: 'Max number of retries'
    default: 3
  remote-name:
    description: 'Remote name to pull from, e.g. origin'
    default: origin
  branch:
    description: 'Branch to pull from, e.g. main'
    default: master
runs:
  using: "composite"
  steps: 
    - name: pull --rebase, then push
      shell: bash
      run: |
        MAX_RETRIES=${{ inputs.max-retries }}
        RETRY_NUM=0
        git pull ${{ inputs.remote-name }} ${{ inputs.branch }} --rebase
        git push
        while [[ $? -ne 0 && $RETRY_NUM -lt $MAX_RETRIES ]]; do
          ((RETRY_NUM++))
          echo "Retrying.. attempt $RETRY_NUM/$MAX_RETRIES"
          git pull ${{ inputs.remote-name }} ${{ inputs.branch }} --rebase
          git push
        done
