name: kusto-syntax-highlighting-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-syntax-highlighting/**'
      - '.github/workflows/kusto-syntax-highlighting-pr-validation.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-syntax-highlighting

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
