name: kusto-color-themes-publish

on:
  push:
    branches:
      - master
    paths:
      - 'kusto-color-themes/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-color-themes

    steps:
      - uses: actions/checkout@v2

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          PACKAGEJSON_DIR:  'kusto-color-themes'
        with:
          default: patch
          tag-prefix: kusto-color-themes-v

      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./kusto-color-themes
