name: kusto-extensions-pack-publish

on:
  push:
    branches:
      - master
    paths:
      - 'kusto-extensions-pack/**'
      - '.github/workflows/kusto-extensions-pack-publish.yml'
  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-extensions-pack

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./kusto-extensions-pack


