name: kusto-color-themes-publish

on:
  push:
    branches:
      - master
    paths:
      - 'kusto-color-themes/**'
      - '.github/workflows/kusto-color-themes-publish.yml'
  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-color-themes

    steps:
      - uses: actions/checkout@v4

      - name:  'Automated Version Bump'
        uses: phips28/gh-action-bump-version@2d294fcd028d7ec0de2fa4e94ad7fe04512cc13a # v11.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          PACKAGEJSON_DIR:  'kusto-color-themes'
        with:
          default: patch
          tag-prefix: kusto-color-themes-v
          # Don't push this commit, because we might not have latest master.
          # We'll fetch, merge, and push at the end.
          skip-push: 'true'

      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./kusto-color-themes

      - name: Push version bump commit
        uses: ./.github/actions/pull-rebase-then-push
        with:
          max-retries: 5
          remote-name: origin
          branch: master
