name: kusto-language-server-publish

on:
  push:
    branches:
      - master
    paths:
      - 'kusto-language-server/**'
      - '.github/workflows/kusto-language-server-publish.yml'
  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-language-server

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name:  'Automated Version Bump'
        uses: phips28/gh-action-bump-version@2d294fcd028d7ec0de2fa4e94ad7fe04512cc13a # v11.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          PACKAGEJSON_DIR:  'kusto-language-server'
        with:
          default: patch
          tag-prefix: kusto-language-server-v
          commit-message: 'CI: version bump [skip ci]'
          # Don't push this commit, because we might not have latest master.
          # We'll fetch, merge, and push at the end.
          skip-push: 'true'

      - run: npm ci
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./kusto-language-server

      - name: Push version bump commit
        uses: ./.github/actions/pull-rebase-then-push
        with:
          max-retries: 5
          remote-name: origin
          branch: master
