name: kusto-color-themes-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-color-themes/**'
      - '.github/workflows/kusto-color-themes-pr-validation.yml'
      - '.github/actions/kusto-color-themes/**'

  workflow_dispatch:


permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-color-themes

    steps:
      - uses: actions/checkout@v4

      - name: Ensure all contributed themes exist in repo
        uses: ./.github/actions/kusto-color-themes/verify
        with:
          working-directory: kusto-color-themes

      - name: Test verify action scripts
        working-directory: .
        run: bash .github/actions/kusto-color-themes/verify/test.sh
