name: kusto-syntax-highlighting-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-syntax-highlighting/**'
      - '.github/workflows/kusto-syntax-highlighting-pr-validation.yml'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-syntax-highlighting

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test
