name: kusto-language-server-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-language-server/**'
      - '.github/workflows/kusto-language-server-pr-validation.yml'
      - '.nycrc.json'

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-language-server

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run vscode:prepublish

  test-and-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-language-server

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: kusto-language-server/server
      - run: npm run test:coverage
        working-directory: kusto-language-server/server
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: kusto-language-server/server/coverage/lcov.info
          flags: unittests
          fail_ci_if_error: false

