name: kusto-extensions-pack-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-extensions-pack/**'
      - '.github/workflows/kusto-extensions-pack-pr-validation.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-extensions-pack

    steps:
      # TODO validate that the extensions listed in the pack exist
      - uses: actions/checkout@v2
